version: '2'
services:
  php:
    build:
      context: .
      dockerfile: php/Dockerfile
    environment:
      XDEBUG_CONFIG: remote_host=${LOCAL_MACHINE_IP}
    ports:
      - "80:80"
    volumes:
      - ./www:/var/www/html
